[package]
name = "cargo-fetcher"
version = "0.7.0"
authors = ["Embark <opensource@embark-studios.com>", "Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
description = "🎁 Experimental alternative to cargo fetch"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/cargo-fetcher"
homepage = "https://github.com/EmbarkStudios/cargo-fetcher"
repository = "https://github.com/EmbarkStudios/cargo-fetcher"
keywords = ["fetch", "gcs", "s3"]
readme = "README.md"

[[bin]]
name = "cargo-fetcher"
path = "src/cmds/main.rs"

[dependencies]
anyhow = "1.0.26"
async-tar = "0.1.1"
async-trait = "0.1.24"
bytes = "0.5.4"
chrono = "0.4.10"
app_dirs2 = "2.0.4"
flate2 = { version = "1.0.13", default-features = false, features = ["rust_backend"] }
futures = { version = "0.3.4" }
http = "0.2.0"
rayon = "1.3.0"
remove_dir_all = "0.5.2"
reqwest = { version = "0.10.1", default-features = false, features = ["rustls-tls"] }
ring = "0.16.11"
rusoto_core = { version = "0.43.0-beta.1", default-features = false, features = ["rustls"], optional = true }
rusoto_s3 = { version = "0.43.0-beta.1", default-features = false, features = ["rustls"], optional = true }
serde = { version = "1.0.104", features = ["derive"] }
structopt = "0.3.9"
tame-gcs = { version = "0.7.0", optional = true }
tame-oauth = { version = "0.4.2", features = ["gcp"], optional = true }
tar = "0.4.26"
tempfile = "3.1.0"
toml = "0.5.6"
tracing = "0.1.12"
tracing-futures = "0.2.2"
tracing-subscriber = "0.2.1"
url = "2.1.1"
walkdir = "2.3.1"
zstd = "0.5.1"

[dependencies.tokio]
version = "0.2.13"
features = ["rt-threaded", "rt-util", "blocking", "process", "macros"]

[features]
default = []
gcs = ["tame-gcs", "tame-oauth"]
s3 = ["rusoto_core", "rusoto_s3"]
s3_test = ["s3"]

[dev-dependencies]
difference = "2.0.0"
tempfile = "3.1.0"
twox-hash = "1.5.0"
walkdir = "2.3.1"

[[test]]
name = "sync_crates_io"
path = "tests/sync_crates_io.rs"
required-features = ["s3_test"]

[[test]]
name = "sync_git"
path = "tests/sync_git.rs"
required-features = ["s3_test"]

[[test]]
name = "diff_cargo"
path = "tests/diff_cargo.rs"
required-features = ["s3_test"]
